### PR TITLE
Milestone I for the Initial Project UI Issue

### LINKED ISSUE #11: Set Up Initial Project UI: Main Page Background and Component Alignment once each of there PR gets merged
## Overview 
**(Please ask to maintainer to assign this issue to you before working on it)**

This issue focuses on setting up the initial UI for the Programming Club website. It includes(both tasks are expected to be done on opening seperate pull request):
1. Setting up the background color for the main page (based on the Figma design).
2. Aligning the components on the main page (once they are created).

This task will be divided into milestones, ensuring incremental progress.

---

### Milestone 1: Set Up Main Page Background Color  **(Completed)**
- Implement the **background color** for the main page as per the [Figma design](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1).
- Ensure the background color matches the branding and design theme.

### Milestone 2: Align Main Page Components (Dependent on Component Creation)
- Once the components for the main page are created (refer to related issues), align them properly.
- Ensure spacing, layout, and alignment adhere to the Figma design.

---

## Steps to Complete Milestone 1
1. Access the **main page** component file (e.g., `App.jsx` or equivalent).
2. Apply the background color from the Figma file to the relevant container(s).
3. Verify the color matches the Figma reference.
4. Create a pull request linking this issue.

---

## Resources
- **Figma Design**: [Link to Figma Design](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1)
---

## Notes
- Coordinate with contributors working on component creation to ensure alignment after their tasks are completed.
- For questions or design clarifications, reach out to the maintainers or refer to the Figma file.

---

**Milestone Progress**:  
- [x] Milestone 1: Background color setup  
- [ ] Milestone 2: Component alignments
   - [x] Navbar
   - [ ] Hero Section
   - [ ] Our Events Component       (Open for contribution)
   - [ ] Upcoming Events Component   (Open for contribution)
   - [x] Contact Component    (Open for contribution)
   - [ ] Footer Component      (Open for contribution)

### PR DESCRIPTION
**Pull request by KushalXCoder**
Resolves #11 Milestone 1

### CODE REVIEW

**Comment by Saumya40-codes** [comment]
Thanks @KushalXCoder for opening your first PR.

As its mentioned in [CODE_OF_CONDUCT](https://github.com/Programming-Club-Ahmedabad-University/WOC-2024/blob/main/CODE_OF_CONDUCT.md)   you should be assigned first (i.e. asking that you will like to work on this issue) before submitting the PR and there cant be duplicate PR for same issue.

Though as there are conflict we will go with this PR as it was submitted first!

**Comment by KushalXCoder** [comment]
Thanks for accepting the PR, next time I would ask first and then work on the issue.

**Comment by Saumya40-codes** [comment]
> Thanks for accepting the PR, next time I would ask first and then work on the issue.

👍

Please address the requested change 
image

**Comment by Saumya40-codes** [comment]
LGTM 🚀

Thanks a lot for this PR @KushalXCoder

**Pull request merged**
