### PR TITLE
OurEvents

### LINKED ISSUE #9: [Component][Design]: Create an Our Events component
Create an "Our Events" section as per the provided design, showcasing various events using cards, images, and typography.

**Approach**

1. **Header:**

- Implement a large "OUR EVENTS" text with layered effects.
  - Use proper font weights and sizes as seen in the design.

2. **Event Cards:**

- Each card contains an image, event name, and additional text/icons.
  - Layout the cards in a grid format for a clean, organized look.

3. **Styling:**

- Use CSS (or framer-motion) for animations, hover effects, and responsive design.
 - Fonts and colors should match the Figma design.
 - Add animations or transitions where needed for smooth visuals.
 

**Additional context**
- Refer to the **Figma design** for layout and styling: [Figma Link](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1).
- You can use **lucide-react** for getting the preferred icons: [https://lucide.dev/icons/]()

**Relevant Images/ScreenShots**
image

### PR DESCRIPTION
**Pull request by Daredevil124**
## Related Issue
Solves/Resolves/Fixes #9.

---

## Description
Provide a detailed explanation of the changes made in this Pull Request [PR].
- Added ourEvents component

---

## Checklist
Please ensure the following before submitting the PR:
- [ ] I have read the `CODE_OF_CONDUCT.md` file and followed it's guidlines.
- [ ] I have followed the design specified in the Figma file (if applicable).

---

## Additional Comments
Include any additional notes or comments for the reviewers. If applicable, mention dependencies, challenges faced, or potential improvements.

### CODE REVIEW

**Comment by Saumya40-codes** [comment]
Looks Perfect 🚀

Nice work @Daredevil124 !!!!

**Comment by Saumya40-codes** [comment]
Can you update the folder name to `OurEvents` instead of `ExampleComponent`, will be more descriptive, so as to what it is.

**Comment by Daredevil124** [comment]
yea sure

**Comment by Daredevil124** [comment]
I have committed and pushed the new code. Would you like me to make a new pull request?

**Comment by Saumya40-codes** [comment]
> I have committed and pushed the new code. Would you like me to make a new pull request?

No all good.

Just make sure that when you make pr or create a new branch it is in line with the base branch

i.e. in your forked repo in `main` (or default one) branch if there is option to `Sync Fork` and the `update` then do it before creating a new branch/pr. This helps from avoiding merge conflict.

LGTM 🚀 otherwise.

**Comment by Saumya40-codes** [comment]
> ## Related Issue
> Solves/Resolves/Fixes #[Issue Number].
> 
> ## Description
> Provide a detailed explanation of the changes made in this Pull Request [PR].
> 
> * Describe the problem or feature being addressed in it.
> * Highlight key modifications in the codebase.
> 
> ## Checklist
> Please ensure the following before submitting the PR:
> 
> * [ ]  I have read the `CODE_OF_CONDUCT.md` file and followed it's guidlines.
> * [ ]  I have followed the design specified in the Figma file (if applicable).
> 
> ## Additional Comments
> Include any additional notes or comments for the reviewers. If applicable, mention dependencies, challenges faced, or potential improvements.

Please add the issue number of the `issue` it is solving

**Pull request merged**
